tasks:
  - init: npm install
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - esbenp.prettier-vscode@3.18.0:SpDMXXww8cAUOXaBCNECgQ==
    - VisualStudioExptTeam.vscodeintellicode@1.2.4:RVTJHzWRjDR0GABZHnWIbA==
    - octref.vetur@0.22.6:xXCsvthKcTcJhinOkpQTjQ==