tasks:
  - init: npm install
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - esbenp.prettier-vscode@3.18.0:SpDMXXww8cAUOXaBCNECgQ==
    - VisualStudioExptTeam.vscodeintellicode@1.2.4:RVTJHzWRjDR0GABZHnWIbA==
    - octref.vetur@0.23.0:0z6KpEz8h/vAvy4pYRDg3Q==
    - dbaeumer.vscode-eslint@2.1.1:DO6k4GCpqhwZcKo+jY9xjQ==