# https://kenchan0130.github.io/post/2018-06-18-1?referrer=https%3A%2F%2Fwww.google.com%2F
# https://esnetk6.com/2018/04/circle-ci-deployment/

 
version: 2
jobs:
  build_deploy:
    docker:
      - image: node:10
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "22:26:f8:10:8d:af:e5:4e:af:4c:8b:a9:e0:d6:76:8b"
      - restore_cache:
          keys:
            - npm-packages-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-packages-{{ .Branch }}
            - npm-packages-master
            - npm-packages-
      - run:
          name: Install Node dependencies
          command: npm install
      - save_cache:
          paths:
            - node_moduels
          key: npm-packages-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Deploy
          command: |
            git config --global user.name "Circle CI"
            git config --global user.email "<>"
            git add -A
            git commit -m "[ci skip] Deploy by CI"
            npm run deploy:github
workflows:
  version: 2
  deploy:
    jobs:
      - build_deploy:
          filters:
            branches:
              only: 
                - master